---

- name: Permitir nfs en firewall
  hosts: all

  tasks:

  - name: Instalar firewalld
    yum:
      name: firewalld
      state: present

  - name: Instalar nfs-utils
    yum:
      name: nfs-utils
      state: present

  - name: Permitir nfs en el firewall
    firewalld:
      service: nfs
      permanent: yes
      state: enabled

